### PR TITLE
fix header not expanding on more chips added to search box, closes #40

### LINKED ISSUE #40: fix search box overflowing chips

### PR DESCRIPTION
**Pull request by JamesAdamHughes**
- Set header height to auto, which expands to fit inside contents. More chips = bigger header

### CODE REVIEW

File: controllers/events.js [hunk 1]
```diff
@@ -3,7 +3,7 @@ var express = require('express'),
 var fs = require('fs');
 
 // API keys to access the skiddle festival database
-var contents = fs.readFileSync(__dirname + '/../public/json_dump/events_dump_23_2_16.json');
+var contents = fs.readFileSync(__dirname + '/../public/json_dump/smaller_dump_23_2_16.json');
```
Comment (louisditzel) [inline controllers/events.js:6]: Why the name change? Can make it smaller without renaming it

Comment (JamesAdamHughes) [inline controllers/events.js:6]: i made a json dump that has fewer events, but wanted to keep the full events dump if i needed

Comment (louisditzel) [inline controllers/events.js:6]: May want to commit that too then ;)
